### ISSUE TITLE
Alter the design to auto discover books

### ISSUE THREAD

**Issue by unhammer** [babluboy/bookworm#104]
I see bookworm installed a cronjob without notifying/asking me, which lead to 100 % cpu usage / battery drain for hours after I had closed the app and having to hunt through `top` to find the culprit. 

It should definitely ask before changing crontab. (Also, it'd be nice if it could, as an alternative, only scan when open.)

**Comment by babluboy** [comment]
Good point. I was not aware that the cron can take 100% CPU and drain battery as its a fairly quick scan which runs once every couple of hours...probably I should throw in a preference option for this:
1- Run a scan every x hours (user can set the value of x)
2- Scan for books after bookworm is closed

The above will only be applicable if the user chooses to set a "watched folder" otherwise there is no scanning at all.

Does the above sound like a good design.

**Comment by unhammer** [comment]
Sounds great to me =D

(I think in my case it was subprocesses of pdftohtml running over a bunch of articles or something, and since it was my first time using bookwork it probably had a lot of work to do.)

**Comment by babluboy** [comment]
@unhammer Yes, the first time is always lot of work and the pdftohtml utility is a very slow process...I already have an issue raised to replace it with something better for PDF rendering...

**Comment by babluboy** [comment]
Thoughts on re-design:
1- Initiate a background process to start the discovery as soon as the user adds/changes a folder. Also show some indication to the user that discovery has been started
2- Initiate a process to check for new books every time bookworm starts

The above can replace the cron job for the auto discovery function.

**Comment by babluboy** [comment]
Altered the design to discover books for auto addition to the library by running a background task when Bookworm is closed. Also updated the dialog to show a Toast message for the same when a directory is added to the "watched list"

![bookworm dialog toast](https://user-images.githubusercontent.com/14061478/33499847-94dd5a40-d6ce-11e7-9e89-c4a076be5cf6.png)
