### ISSUE TITLE
Publish on AppCenter

### ISSUE THREAD

**Issue by Vuneu** [babluboy/bookworm#108]
Would love to see Bookworm on the Appcenter, any chance that could happen?
Thanks!

**Comment by babluboy** [comment]
@Vuneu Bookworm is already on Appcenter since quite a while (one of the first apps to get there !). You can search for bookworm or use this nice sticker to get to Bookworm directly on Appcenter:

[![Get it on AppCenter](https://appcenter.elementary.io/badge.svg)](https://appcenter.elementary.io/com.github.babluboy.bookworm)﻿

**Comment by Vuneu** [comment]
Not sure how I missed this, thanks!
