### ISSUE TITLE
Keyboard Shortcut for Split (Two Page) View

### ISSUE THREAD

**Issue by momoe** [babluboy/bookworm#110]
First let me say I'm loving having a clean simple ePub reader for linux that fits right in with the desktop UI. 
I just launched the app after an update today and noticed it's in a split colum view. Is this a new feature? 

If this is so would be nice to have an keyboard shortcut to toggle single or split view. 

Also would be a further improvment  to only display the current window frame's worth of contents instead of scrolling all the way down through the each xhtml file in ebooks.

**Comment by babluboy** [comment]
@momoe Thaks for your interest in Bookworm...Guess you are either building from source or using the daily PPA...the split view (two page view) is something I was working on yesterday and just pushed to the PPA, so you are stuck with a two page view without having the control to flip back to a single page view... ...completed the control to toggle between normal and two-page views today and will push to the daily PPA shortly...so you should be getting the control to toggle in a few hours....

Like your idea of putting in a keyboard shortcut for toggling between single and two page views...We can use this issue to track the keyboard shortcut...design questions:
1- What should be the keyboard shortcut for two page - is there something standard ?
2- The shortcut should only be on the reading view (not on the library view) as that is where it will make sense

Let me know your thoughts on the above....

Here is how the control looks like in the preference view at the moment
![two page view 1](https://user-images.githubusercontent.com/14061478/29002706-6ae572d4-7aa0-11e7-920a-e10cbf2e450f.png)

**Comment by babluboy** [comment]
On the second issue you have sighted, I had thought of this initially with a no vertical scrollbar view (like iBooks on iOS)...but have not done it yet due to two reasons:
1- Webkit2 removed the control on the scrollbar which makes it hard to implement using the DOM
2- I read somewhere that free flow type rendering should allow the text to flow for vertical scrolling
3- Some technical challenges in implementing the page number based on the size of the view content i.e. resizing the window to smaller view will lead to change of content displayed on the page and hence the numbering...

May be I will get around to this no-vertical-scroll design after getting in the more important updates like PDF rendering, etc...

**Comment by babluboy** [comment]
Also out of interest, are you using Bookworm on a distro other than Elementary OS ? Will be good to see a screen shot of how bookworm looks like on your distro :-)

**Comment by momoe** [comment]
@babluboy Yes, I've been building it from source from the AUR source list. I've been looking for a light weight ePub reader that cleanly integrates into the GNOME look. 
To answer your questions, I would probably put the keyboard shortcut as something either related to it's category (View) or something sensible in it's name. For example Ctrl_D would toggle double page mode on/off.

Alternatively since the default to full screen; another view shortcut, is f11, maybe f10 would be an option. 

But I would still leave the field open to change per user in preferences. 

And yes, having a set of shortcuts for Reader mode and Library mode would be sensibly sensible. 

I hope this is useful. If you're interested in taking the split view a step further, adding a "shadow" svg texture down the middle would give it the illusion of a real book. I'll mock something up in Inkscape and post it below.
![deepinscreenshot_20170807032308](https://user-images.githubusercontent.com/19848666/29022933-475cb086-7b20-11e7-837e-85f65aa3e143.png)

**Comment by m-delvalle** [comment]
+1 to the shadow, as long as it's _optional_ ;)

**Comment by babluboy** [comment]
@momoe Thanks a lot for the suggestion and for the screenshot. Bookworm looks ok on Gnome - maybe I should spin up a VM and test it...one thing I noticed though it the style classes are not applied to the Library button...probably I should add a fallback style class to the code
![screenshot from 2017-08-08 08 18 43](https://user-images.githubusercontent.com/14061478/29060566-37948fe6-7c12-11e7-8f8f-df62026ab05b.png)

I will not be able to use Ctrl+D as the shortcut since I have already used it for toggling bookmarks...F10 is available but will check to do if some shortcut for two page view is used commonly across ebook readers and stick to the same for consistency....same for the shortcut between Grid View and List View - need to check what Elementary OS uses in Files and will follow that....

Personally for me the shadow looks great but looks like it is a personal preference as @m-delvalle has suggested, so can end up adding this to the Preference menu as a  stylization theme...I have seen the stacked edges on some readers as well, but kind of looked old school to me...will check further...

**Comment by momoe** [comment]
My screenshots are based on a community release of Deepin (Manjaro) so the scheme window theme here isn't 100% GNOME perse, but a derivitive of it. Some buttons might not look 1:1, but still looks good. And yes, the shadows could be toggle options I guess, I've posted the svg source there if you want to use it.

**Comment by thrustix** [comment]
![screenshot from 2017-08-22 03-10-24](https://user-images.githubusercontent.com/1668049/29543132-95d75ee6-86e7-11e7-8501-e6ac607185bb.png)
Two Page Layout isn't rendered properly, i.e. you must scroll down to read left pane, before continue reading right pane, which is against the whole point of Two Page Layout.
ArchLinux AUR package: bookworm-git, v.0.9.1

**Comment by babluboy** [comment]
@thrustix Thanks for the comments and agree with your thoughts, however Bookworm has not adopted the fixed page layout - it is still using the flow layout which means the vertical scroll bar is required ....
The two page layout just divides the contents into two sections...if after the division the content is still larger for a single section it still requires scrolling....hopefully when I figure out how to convert the contents to a fixed page size, this issue will be resolved...

**Comment by babluboy** [comment]
Pushed some changes to toggle between List View and Grid View with "Ctrl + L" keyboard shortcut

**Comment by babluboy** [comment]
Pushed some changes to return to Library View from Reading View with "Ctrl + B" keyboard shortcut
