### ISSUE TITLE
Unreliable search

### ISSUE THREAD

**Issue by sojusnik** [babluboy/bookworm#113]
The search function is very unreliable. Take f.i. this [epub](https://mega.nz/#!fsxVmAhC!dGncKDhbE51jliWJz76z0MVDRiiByi7H_tyao2FlK1U).

If you search for `But, to–day, I greatly fear that my King is dead,` it won't be found, although it's in the first paragraph. I assume it's because of the `–` sign as you'll see in the search results. Other characters like `'` are also affected, like in `it’s seven hundred million`.

But then there is the following strange case: Try to find `there are` and you'll get only one result, although there are several of them in this epub. The same is true for `food`.

I also think, that searching for `room` should also find `rooms`, but currently it doesn't. The search is already case-insensitive though. That's good!

I'm also looking forward to have the [search highlighting feature](https://github.com/babluboy/bookworm/issues/103) soon. It would be very handy, especially to solve the current search problems.

Many thanks for creating Bookworm! It's currently (one of) the best epub readers out there for Linux.

**Comment by babluboy** [comment]
@sojusnik Thanks for raising this issue. I have replicated the issue. if I remove the `But, to–day` from the search string, then the result comes up as : `and policy all complete. But to&#8211;day, I greatly fear that my king is dead, and if I want a crown I must go and hunt it for`...so you are indeed spot on, the issue is that the search is being made on the contents of the book which has the escape char for the "-". 

I'm currently running the following grep command to search for the user text on the html content of the book...
`grep -i -r -o -P -w '.{0,50}"+BookwormApp.AppHeaderBar.headerSearchBar.get_text()+".{0,50}' "`

one way to fix this is to run the search on the as-is user provided string and also a modified version of the user provided string which contains the escape chars as needed...

**Comment by babluboy** [comment]
Fixed the issue of only one search result per html file...pushed to master and the daily ppa.
Need to focus on the handling of HTML escape chars which is causing the issue of search not working if the user provided phrase has special chars like -, ', <, etc...

**Comment by babluboy** [comment]
Finally settled for the "html2text" utility for the solution. The fix I pushed just now takes care of the following:
1- Searches correctly even when the search string has a special character i.e. – or '
2- If more than one result is found for the search string on a page then all of them are returned
3- word subsets are now supported, i.e. searching for room should also find rooms

The changes are in the master and also on the daily PPA. Please re-open if you find any issues with this fix. Will be great if any testing can be done.
