### ISSUE TITLE
Shortcuts for search

### ISSUE THREAD

**Issue by sojusnik** [babluboy/bookworm#120]
Would be nice to have a shortcut to focus the search field with `Ctrl+f` and `Ctrl+g` to jump to the next search result in the text. If `Ctrl+g` goes forward, then `Shift+Ctrl+g` should go backwards, as it's done in other programs too.

**Comment by sojusnik** [comment]
Other useful shortcuts could be:

`Ctrl+w` to close the current book and open the library view.
`Ctrl+q` to close Bookworm entirely.

**Comment by babluboy** [comment]
@sojusnik Pushed an update for the following shortcuts :
Ctrl+L : to close the current book and open the library view.
Ctrl+Q : to close Bookworm entirely.

**Comment by babluboy** [comment]
@sojusnik Added the Ctrl+F shortcut for focusing on the search. However instead of adding shortcuts for navigating the search list, I added focus on the first link and the keyboard up/down arrow keys can be used for navigation of the link and the enter key to select a specific search result to jump to that page. I hope this achieves the objective of searching for text and navigating to a specific search result without leaving the keyboard.

pushed [commit](https://github.com/babluboy/bookworm/commit/a6a3c5109bc8f310ebcd97f99120ef769827c671) here for the above changes.

Please feel free to test if possible from master/daily ppa and comment.
