### ISSUE TITLE
Focus problem on Buttons

### ISSUE THREAD

**Issue by choyan** [babluboy/bookworm#13]
Whenever I try to click on those 2 header buttons, they do not provide appropriate interaction. They should be rounded properly.
![screenshot from 2017-02-25 18 17 28](https://cloud.githubusercontent.com/assets/1283240/23330987/e64020f8-fb86-11e6-9ce1-6b00b7cbc9e4.jpeg)

**Comment by babluboy** [comment]
hi thanks for testing bookworm as i work on it and raising issues...I believe the round shadow is not coming maybe because the aspect ratio of those icons are not correct or I need to do something in the code to assign the right interaction shadow....I will look into it in due course. Thanks again for taking time in raising this bug.

**Comment by choyan** [comment]
Actually I was always wondering about having an elemnetary Ebook reader. Watching you to work on it, is kind of fulfilling my dream. Thank you very much for working on it. I will try to keep testing it till the end :)

**Comment by babluboy** [comment]
@choyan Many thanks for the motivation. Testing is a big task, I was thinking of setting up Test Cases for Bookworm on GitHub as the functionality grows so that it will be easy to test when releasing stable versions later (I keep forgetting test cases even now). Will let you know when I set it up and you can give suggestions.

Do let me know if there is any aspect of Bookworm you would like to contribute i.e. artwork, CSS and of course if you want to do vala coding...

**Comment by choyan** [comment]
@babluboy Thank you very much for this opportunity.
I am a Front-end Developer. As far I can help at the moment is, working with CSS of the app GTK and Setting up the App website. Vala is not my strongest point to help yet.  I would love to have a discussion with you about this if you have time :)

**Comment by babluboy** [comment]
@choyan Sure we can have a chat sometime, looks like you are based out of Dhaka from your profile. I'm currently in London, but we can find a way to overcome the time difference :-)

**Comment by choyan** [comment]
@babluboy , I am sending you a mail. We can chat on Google Hangout, if time mathches sometime :)

**Comment by babluboy** [comment]
Replaced the local images with icons from the Elementary Icon set and the interaction shadow on the icons are appearing properly as round shadows
![screenshot from 2017-04-25 18 23 29](https://cloud.githubusercontent.com/assets/14061478/25398581/80b0ebc8-29e4-11e7-9d63-f97a468206d8.jpeg)
