### ISSUE TITLE
Table of Content button on Homepage

### ISSUE THREAD

**Issue by choyan** [babluboy/bookworm#14]
I think Table of content button only should be available, whenever a user is reading a page. I would like to propose a design concept here from Photos app. 
Just like the Photos app, Bookworm will show show a "Library" navigation button to navigate to Library view. And maybe sidebar of the app will show the table of contents, whenever a user clicks on the expand button below. Which can also be Hidden.
![screenshot from 2017-02-25 19 15 46](https://cloud.githubusercontent.com/assets/1283240/23331367/e6343efc-fb8e-11e6-9152-020cfe793f2c.jpeg)

Currently the cover image of any ebook is stretched to the full width. If it would be possible life "Easy Ebook Viewer" to specify the cover image and give it a certain width to be stretched. So that, the Cover Image would look much beautiful
![screenshot from 2017-02-25 19 21 17](https://cloud.githubusercontent.com/assets/1283240/23331419/ec678864-fb8f-11e6-8692-b76c15bf8e86.jpeg)

**Comment by babluboy** [comment]
Thanks for the suggestions, there are three issues you have listed:

1. Content View button should only be visible in the reading mode - This is sensible (and easy to achieve as well), I will be able to push it out quickly
2. The Navigate to Library button should be like an arrow - I have seen this in the Settings, will try and use that instead of the four square button I'm using
3. Having a side bar to show table of contents instead of a contents page so that the user can flip back easily to the page being read if he decides not to jump to a different page. And if the user does decide to jump to another page then the content side bar should dissapear - Again a sensible design, but one that will take some considerable code to achieve. Will try to get this done soon.
4. Showing the correct image of the book cover - This is something I had in mind as well. At the moment unless the ebook specifies a size for the image the image fills the whole content area and appears stretched. Will try to see if I can handle this situation by over riding this behavior. For some ebooks I have which specify size the image comes nicely as shown below.

![screenshot from 2017-02-25 14 00 51](https://cloud.githubusercontent.com/assets/14061478/23331702/e5133a22-fb62-11e6-9662-ea127b845401.jpeg)

**Comment by choyan** [comment]
Exactly. I will  keep informing if anything comes on my mind :)
Thank you very much.

**Comment by babluboy** [comment]
@choyan 
#1 Content View button should only be visible in the reading mode - completed this and pushed the code to both PPA and Git. Do you get Bookworm from the PPA ?(should be the quickest way to get the updates I make)

**Comment by babluboy** [comment]
@choyan I have made a fix for the URL of images, so hopefully some of the ePubs which had relative links and come up with broken/missing images will now work properly. Will be good to know when you test

**Comment by babluboy** [comment]
@choyan Last update for today - Implemented the Back Arrow Library button and also hid the Library button in the library view. The Library button is only required in the Reading view but has no use in the Library view. Let me know if you feel the behavior is fine and the code works as expected.

**Comment by babluboy** [comment]
@choyan Many thanks for checking this out - must have been a bit sleepy when i pushed out yesterday's changes and did not make the org id changes correctly :-) I was able to replicate the same with my VM and now I have fixed the org id and pushed the code to both the PPA and Git. Hopefully you should be able to do some testing now. Here are the changes I did yesterday:
1- Updated Org Id
2- Updated the Back Button to go back to Library view from the Reading View
3- Removed the Back Button on Library view (the button is only present on the reading view)
4- Made some fixes to display images for some types of ePubs

Note: In case of the app crashing, you can test from the command line with "bookworm --debug". That will print all the debug commands I have put in the code at various places and will tell me where the code is failing. The terminal output you provided in the email helped me pin point the issue with the org id

**Comment by choyan** [comment]
Great! It's working again now. I built the files from source again. PPA is a bit late here always :)
All issues you've solved are working great now. :+1:

**Comment by babluboy** [comment]
I have moved (3) and (4) to separate Issues to manage it more easily - see #18 and #19.
Closing this as the first two are resolved
