### ISSUE TITLE
Book contents are replicated upon reselection from library

### ISSUE THREAD

**Issue by BasioMeusPuga** [babluboy/bookworm#141]
Steps to reproduce:
1. Open a book
2. Click on the `Library` button
3. Reopen the book

The entire contents of the book are added to the its end. This happens every time the process is repeated.

**Comment by babluboy** [comment]
@BasioMeusPuga Thanks for your interest in bookworm and taking the time to test.
Is your version built from master or the daily PPA i.e. 0.9.1 ? I am not able to replicate the issue. 
Can you show a screen shot of the issue. Are you referring to the actual content of the book shown on a page or are you referring to the table of contents that is shown by clicking on the info button on the headerbar?  

Also try adding a book and see if the issue is occurring that will help isolate the issue between new and existing books.

Since I recently changed the DB structure by splitting the library data and the book data , I'm wondering if the table of content is being picked from two locations....

**Comment by babluboy** [comment]
@BasioMeusPuga Please ignore my comments above, I have replicated the issue and its indeed the table of Contents which is being repeated every time the book is opened. Should be an easy one to fix.

**Comment by babluboy** [comment]
@BasioMeusPuga I think I have fixed the bug - the meta data of the book was being loaded from DB each time the book was opened and that caused the content section to be appended. Added the code to load the meta data only if it has not been loaded. This should fix the issue as well as make the loading more efficient if the same book is opened multiple times as the DB loading is not used after the first time.
