### ISSUE TITLE
Errors during 'make'

### ISSUE THREAD

**Issue by momoe** [babluboy/bookworm#142]
I'm pastebin-ing the build process for hopes of finding out what the error was during the make section of the update. 

https://pastebin.com/T29PCrnK

**Comment by mmetak** [comment]
Seems like new line `\n` at the end causes this?
https://github.com/babluboy/bookworm/blob/260952900ae72eaddb4231104dcb191286ff8d52/po/fr.po#L42

**Comment by babluboy** [comment]
@momoe Thanks for raising this issue. The code was indeed breaking due to the "\n" in the translation string. The translator had corrected the same [here](https://hosted.weblate.org/translate/bookworm/bookworm/fr/?checksum=ebf502e1d5bdbe86) but not committed.
I have now committed and the build succeeded.  Hopefully, you can now proceed your build.
