### ISSUE TITLE
Library issues for auto addition of books

### ISSUE THREAD

**Issue by caio-hungria** [babluboy/bookworm#143]
I had a problem in my library view, where most of my books were duplicated. Some books were displayed even six times. Simply removing and reinstalling the app didn't fix the issue. So I tried to remove bookworm completely, by removing bookworm folders in ~/.cache and ~/.config as well.

Now I installed it again and even though I don't have duplicated books anymore, bookworm won't sync all of my books. Just a smal fraction of it. And it was strange that it synced a small part of my library, and then some more. It was a strange thing, because it used to sync all my books before.

What can I for it to sync everything?

Some screenshots:
![captura de tela de 2017-11-04 12 15 58](https://user-images.githubusercontent.com/26253498/32409419-9f970dba-c192-11e7-9b85-b511db364705.jpeg)
![captura de tela de 2017-11-04 16 21 55](https://user-images.githubusercontent.com/26253498/32409420-9fb8d440-c192-11e7-80f4-1832d50c9a36.jpeg)
![captura de tela de 2017-11-03 18 20 23](https://user-images.githubusercontent.com/26253498/32409427-bdb5e9ce-c192-11e7-8c2b-9022577975a5.jpeg)

**Comment by babluboy** [comment]
@caio-hungria Thanks for raising the issue - will look to figure out where its going wrong.
Regarding books appearing multiple times, this can happen if the same book is present in multiple formats (or in the same format at different locations).

At the moment, there is a cron job which runs the process of scanning books in the watched folder and attempting to add them to the bookworm DB. Your machine needs to be running at the time of this cron job which is scheduled at every even hour (I'm looking to change this behavior soon). You can check this by running `crontab -l`. If your machine is shutdown while the cron is running then the books will not be added completely.

If you can run `bookworm --discover` it should run the process of finding the books under the watched folders and add it to the bookworm libraries. Maybe that can give a clue if its crashing when its not able to add a book due to any parsing issue (maybe explains why its not able to add all books). If this is indeed the case then I can add some error handling to prevent the process from stopping if certain books cannot be added.

Please provide your findings for the above which will help debug the issue and perhaps I can then fix it. Thanks again for making bookworm better.

**Comment by caio-hungria** [comment]
attempting to add book located at:/home/caiohung/Documentos/Ebooks/Literatura/Italo Calvino - Italy/English/Italo Calvino - Six Memos for the Next Millennium.epub[WARNING 23:05:43.917510] [GLib] Invalid file descriptor.
[WARNING 23:05:43.926289] utils.vala:106: Error encountered in execution of sync command [unzip -o "/home/caiohung/Documentos/Ebooks/Literatura/Italo Calvino - Italy/English/Italo Calvino - Six Memos for the Next Millennium.epub" -d "/home/caiohung/.config/bookworm/books/Italo Calvino - Six Memos for the Next Millennium.epub"]:   End-of-central-directory signature not found.  Either this file is not  a zipfile, or it constitutes one disk of a multi-part archive.  In the  latter case the central directory and zipfile comment will be found on  the last disk(s) of this archive.note:  /home/caiohung/Documentos/Ebooks/Literatura/Italo Calvino - Italy/English/Italo Calvino - Six Memos for the Next Millennium.epub may be a plain executable, not an archiveunzip:  cannot find zipfile directory in one of /home/caiohung/Documentos/Ebooks/Literatura/Italo Calvino - Italy/English/Italo Calvino - Six Memos for the Next Millennium.epub or        /home/caiohung/Documentos/Ebooks/Literatura/Italo Calvino - Italy/English/Italo Calvino - Six Memos for the Next Millennium.epub.zip, and cannot find /home/caiohung/Documentos/Ebooks/Literatura/Italo Calvino - Italy/English/Italo Calvino - Six Memos for the Next Millennium.epub.ZIP, period.
[WARNING 23:05:43.926680] ePubReader.vala:122: Mime Content file could not be located at expected location:/home/caiohung/.config/bookworm/books/Italo Calvino - Six Memos for the Next Millennium.epub/mimetype

Attempting to add book located at:/home/caiohung/Documentos/Ebooks/Literatura/Coetzee, J M/Childhood of Jesus/Coetzee, J. M. - Childhood of Jesus (Harvill Secker, 2013).epub[WARNING 23:05:43.966041] [GLib] Invalid file descriptor.
[WARNING 23:05:43.985921] [GLib] Invalid file descriptor.
[WARNING 23:05:43.986033] [GLib] Invalid file descriptor.
[WARNING 23:05:43.986160] [GLib] Invalid file descriptor.
[WARNING 23:05:43.986364] [GLib] Invalid file descriptor.
[WARNING 23:05:43.989845] [GLib] Invalid file descriptor.
[WARNING 23:05:44.105141] [GLib] Invalid file descriptor.
Sucessfully added book located at:/home/caiohung/Documentos/Ebooks/Literatura/Coetzee, J M/Childhood of Jesus/Coetzee, J. M. - Childhood of Jesus (Harvill Secker, 2013).epub
Attempting to add book located at:/home/caiohung/Documentos/Ebooks/Literatura/Coetzee, J M/Foe/Coetzee, J. M. - Foe (Penguin, 1987).pdf[WARNING 23:05:44.140491] [GLib] Invalid file descriptor.
[WARNING 23:07:05.059604] [GLib] Invalid file descriptor.

I cancelled the process once it got stuck there and tried again. This is what I got:

Attempting to add book located at:/home/caiohung/Documentos/Ebooks/Literatura/Italo Calvino - Italy/English/Italo Calvino - Six Memos for the Next Millennium.epub[WARNING 23:12:40.903851] [GLib] Invalid file descriptor.
[WARNING 23:12:40.907033] utils.vala:106: Error encountered in execution of sync command [unzip -o "/home/caiohung/Documentos/Ebooks/Literatura/Italo Calvino - Italy/English/Italo Calvino - Six Memos for the Next Millennium.epub" -d "/home/caiohung/.config/bookworm/books/Italo Calvino - Six Memos for the Next Millennium.epub"]:   End-of-central-directory signature not found.  Either this file is not  a zipfile, or it constitutes one disk of a multi-part archive.  In the  latter case the central directory and zipfile comment will be found on  the last disk(s) of this archive.note:  /home/caiohung/Documentos/Ebooks/Literatura/Italo Calvino - Italy/English/Italo Calvino - Six Memos for the Next Millennium.epub may be a plain executable, not an archiveunzip:  cannot find zipfile directory in one of /home/caiohung/Documentos/Ebooks/Literatura/Italo Calvino - Italy/English/Italo Calvino - Six Memos for the Next Millennium.epub or        /home/caiohung/Documentos/Ebooks/Literatura/Italo Calvino - Italy/English/Italo Calvino - Six Memos for the Next Millennium.epub.zip, and cannot find /home/caiohung/Documentos/Ebooks/Literatura/Italo Calvino - Italy/English/Italo Calvino - Six Memos for the Next Millennium.epub.ZIP, period.
[WARNING 23:12:40.907350] ePubReader.vala:122: Mime Content file could not be located at expected location:/home/caiohung/.config/bookworm/books/Italo Calvino - Six Memos for the Next Millennium.epub/mimetype

Attempting to add book located at:/home/caiohung/Documentos/Ebooks/Literatura/Carroll, Lewis/Mathematical Recreations/Carroll, Lewis - Mathematical Recreations (Dover, 1958).pdf[WARNING 23:12:40.954564] [GLib] Invalid file descriptor.

It's so strange, because it used to work perfectly. Is it possible that I removed a dependency or a specific package? I removed a lot of unused softwares in my AppCenter. Maybe something that shouldn't be removed ended up being removed. Some libs, maybe. Python? I don't know, I'm just trying to guess here.

Thank you so much for your patience.

**Comment by caio-hungria** [comment]
I think that this problem is caused by the fact that I deleted some folders off bookworm, on the hope that I could fix the duplicated issue. So I ended up with a worse scenario, where I can't import books at all. 
What can I do to fix it?

**Comment by caio-hungria** [comment]
When I remove bookworm, the configuration files, the data, etc, are not removed of the system as well. What happens is, I remove it through AppCenter, I install it again, and I still get the same problem than before. Because it will "reload" existing data, existing configuration files or whatever. I wish I could remove it entirely and then install it fresh and clean, so I could scan my library and have all my books displayed there.

**Comment by caio-hungria** [comment]
Have you seen the latest elementary post?
https://medium.com/elementaryos/granite-0-5-is-here-dafc4436ac09
"AsyncImage
Granite.AsyncImage is a Gtk.Image subclass that loads icons and images without blocking the main Gtk thread. This is a tremendous performance booster if your UI has a large image grid like an album or cover art view."

don't know if it's relevant, but I thought this could be useful to bookworm.

**Comment by babluboy** [comment]
@caio-hungria I believe the issue you are facing is due to some files which cannot be parsed. Try the following:
1. /home/caiohung/Documentos/Ebooks/Literatura/Italo Calvino - Italy/English/Italo Calvino - Six Memos for the Next Millennium.epub : Try to right click on the file and choose "extract here". From the error message it looks like zip is not able to uncompress this file.

2. /home/caiohung/Documentos/Ebooks/Literatura/Coetzee, J M/Childhood of Jesus/Coetzee, J. M. - Childhood of Jesus (Harvill Secker, 2013).epub : This seems to have been added successfully.

3. Bookworm keeps all its files in the directory ~/.config/bookworm. This includes the database, cover images and cached contents. You can remove the directory ~/.config/bookworm to remove all data - perhaps thats worth a try.

4. Yes, I have seen the granite0.5 release and asked some initial questions to Dan on the availability of the library on other linus distros. I will definitely adopt the new libraries for the perf. boost and other features as soon as it is supported/available on a wider set of distros.

Let me know how you get along.

**Comment by caio-hungria** [comment]
Yes, it is working now. It's importing the files. But there are still, a lot of duplicated or multiple entries for almost every book. And I don't have duplicate books in my system.
Another problem that I have, is that everytime I open the app it has to reload the entire library, which takes a while.
![captura de tela de 2017-11-06 09 22 00](https://user-images.githubusercontent.com/26253498/32439113-6c933932-c2d4-11e7-8ac0-477d9e7a7c00.jpeg)

**Comment by caio-hungria** [comment]
Maybe i's happening because I have a really large library, with more than a thousand books.

**Comment by babluboy** [comment]
@caio-hungria Nice that its working now...did you remove the ~/.config/bookworm folder to get it working or did you remove any corrupt ePub which was stopping the discovery process? Will be good to know what was the real issue and if I need to fix something to avoid the same problem for other users...

Can the reason behind multiple books be the fact that the same book is in multiple formats - at the moment bookworm loads the same book even though the title is the same (will add a preference item to avoid this - #124 )

Regarding the slow loading for a large library, I had this issue in mind and have opened issue #146 to track the same. However, I had made the loading of books a non blocking process, so for example you can choose the first book to read while the others are getting loaded. 

Another tip to avoid the library loading -  close bookworm in the reading mode then when you open next time, it should avoid loading the library and directly open the  the page you were last reading - make sure you have the "Always show library at start" option disabled in the settings.

**Comment by caio-hungria** [comment]
@babluboy thank you so much for your patience again.
The problem was indeed one corrupted file that stopping the whole process. No problems there, I guess.

About the library, I think there should be a nice solution somewhere. Music players seems to handle this quite well. Even Noise does it well. I don't have any programming skills, but maybe it could work on the same principle? ( pardon my ignorance, just guessing here )

As for the duplicated and multiple books, I'm trying something else. I won't import it through the terminal. I will let it work by itself. So far so good, I have a few books on my library already, but none of them are duplicated.

As for the default importing behavior. 

"At the moment, there is a cron job which runs the process of scanning books in the watched folder and attempting to add them to the bookworm DB. Your machine needs to be running at the time of this cron job which is scheduled at every even hour (I'm looking to change this behavior soon). You can check this by running crontab -l. If your machine is shutdown while the cron is running then the books will not be added completely."

I don't think that's a good solution, because if an user does miss the auto importing scheduled time, it might seem like the app won't import books at all. I think this whole process should be more straight forward. Maybe the app should start importing books by the time it opens?

Also, when bookworm is loading pdfs, it gets really heavy on my system as you can see on the screenshot. with 60% of cpu usage. And most of the time it reached 80~86% of cpu usage.

![captura de tela de 2017-11-05 23 14 34](https://user-images.githubusercontent.com/26253498/32441117-2f05d0da-c2dd-11e7-9170-05f6b00d45a9.jpeg)

**Comment by babluboy** [comment]
@caio-hungria Thanks for the details. I see a few actions:
1- eBook discovery process stopped if a eBook is corrupt : I would need to fix this as it should ideally catch the issue and continue the process for other books.
2- Redesign importing behavior : I will track this by issue #104 
3- PDF Issue : PDFs need to be converted to HTML files so that all the functions of reading, annotation, search, etc. can be uniformly applied. However, at the moment there are two issues (i) instead of storing the chapter names in the DB all the individual pages are stored which bloats the DB and (ii) the PDF to HTML utility takes up a lot of processing power as indicated by the CPU usage. This is tracked by Issue #82 

Closing this issue, but feel free to comment for any additional thoughts.

**Comment by caio-hungria** [comment]
I would double check if a corrupt ebook does stop the process indeed,  or if I had something wrong in my system. So I don't know if the issue #147 is really an issue.
It's good to see that the problems I've talked about were already raised:
- Performance issues when importing PDFs
- large .config/bookworm folder
As for the importing redesign, I do have some thoughts. I think importing should begin to happen when the user opens the app and not after the user closes the app. If the user selects a folder to scan and nothing visible happens right away, it feels like the app is not working, that the app is broken or doesn't work. Also, bookworm shouldn't reload the library everytime the user opens the app. Should be like in music players, instantly available. As matter of fact, I think bookworm importing and library behavior should be exactly like music players apps, like elementary Noise app. Please, consider this.
The app is incredible, really. I checked, there is nothing like it in Windows or Mac. Later on you can think to port it to other systems, if it's worth, of course. awesome work.
Best regards.
