### ISSUE TITLE
Search results within a book is not shown in a logical order

### ISSUE THREAD

**Issue by forteller** [babluboy/bookworm#144]
I don't think so at least. I would think that the result would be shown in the order they appear in the book. But they don't, and I don't understand which order they're shown in. If there are results for the word "book" in chapter 1, 4, 7 and 20 I would prefer if the results are shown in that order, not like now when it's shown more like 7, 20, 1, 4.

Thanks!

**Comment by babluboy** [comment]
@forteller Can you please check what version of bookworm you are running - is it 0.9.1 or 0.9. 

In v1.0, I checked a couple of books and the search results show up in order of the chapter and in the order of occurrence within a chapter.

![screenshot from 2017-11-06 20 32 09](https://user-images.githubusercontent.com/14061478/32462675-21ab3560-c332-11e7-87d7-b98ad087653a.png)

**Comment by forteller** [comment]
Great to hear that it's been fixed. I have version 0.9.1. I'll probably test the nightly PPA later :)

**Comment by babluboy** [comment]
@forteller Hmm..If you are seeing this issue in 0.9.1 then I dont think it will be fixed (I was hoping you had the 0.9 version)...but let me know after you check and I can investigate further...

**Comment by babluboy** [comment]
@forteller Let me know if you managed to update to Bookworm 0.9.2 and if this issue still persists, then please re-open this issue for me to check.

**Comment by forteller** [comment]
Hi. Trying to upgrade I just get this message:
![screenshot from 2017-12-01 21-45-22](https://user-images.githubusercontent.com/343561/33502587-9ab130d6-d6d8-11e7-86da-5d776552804a.png)

I'm using this PPA: http://ppa.launchpad.net/bookworm-team/bookworm/ubuntu

And I'm on Ubuntu 17.10 64 bit

**Comment by babluboy** [comment]
@forteller I think its due to bookworm using the latest version of granite (0.5) - the [toast in dialog](https://github.com/babluboy/bookworm/issues/104#issuecomment-348593394) which I introduced in todays change
Latest version of Granite: [https://medium.com/elementaryos/granite-0-5-is-here-dafc4436ac09](https://medium.com/elementaryos/granite-0-5-is-here-dafc4436ac09)
Launchpad Granite Package: [https://launchpad.net/granite](https://launchpad.net/granite)

Will be great if you can install granite 0.5 and then try installing bookworm.
