### ISSUE TITLE
Apply a book's original stylesheet

### ISSUE THREAD

**Issue by mauforonda** [babluboy/bookworm#151]
Is there a way to apply a book's original stylesheet? Bookworm seems to ignore all bundled css definitions. Thanks

**Comment by babluboy** [comment]
@strangel8p While I have added some overriding CSS for some font/size control the original stylesheet is still intact and should be referred correctly.  Any chance you can attach the eBook or email the same to me so that I can investigate.

**Comment by strangel8p** [comment]
You are right, many books were rendering wrong because their stylesheets lacked @charset and @namespace rules. Maybe add a rule in provideContent to add them automatically?

**Comment by babluboy** [comment]
@strangel8p Would you be able to provide two books - one with the good stylesheet and the one without a good stylesheet so that I can compare and see if I can force some improvements where needed

**Comment by strangel8p** [comment]
Sure. On [epubtest.zip](https://github.com/babluboy/bookworm/files/1464079/epubtest.zip) Bookworm renders `good.epub` fine and ignores all bundled css on `bad.epub`. The only difference being that `bad.epub` lacks the following lines preceding each stylesheet: 

```
@charset "utf-8";
@namespace epub "http://www.idpf.org/2007/ops";

```

**Comment by strangel8p** [comment]
Sure. On [epubtest.zip](https://github.com/babluboy/bookworm/files/1464079/epubtest.zip) Bookworm renders `good.epub` fine and ignores all bundled css on `bad.epub`. The only difference being that `bad.epub` lacks the following lines preceding each stylesheet: 

```
@charset "utf-8";
@namespace epub "http://www.idpf.org/2007/ops";

```

**Comment by babluboy** [comment]
@strangel8p Thanks for the two epubs and I can see the difference due to the difference of the namespace and charset...however, not all books have stylesheets and the epub specs donot specify the location of a stylesheet which I can use to check if a epub contains a stylesheet and then check if it contains the namespace and charset....

one rough way will be to search for all the files in a epub container and spot any stylesheets by searching for files with the .css extension and then search and add the namespace and charset if they are not present...however many ebooks contain in-line css which will fail the above method...

any thoughts?

**Comment by babluboy** [comment]
also there are multiple css files in the book i.e. page_style.css and stylesheets.css - not sure if the namespace and charset need to be added to each of them...I added it to both on the bad epub and it worked fine...but not sure if I should do that addition blindly to every .css file in the epub ?

**Comment by babluboy** [comment]
Closing this as this was related to epubs which has incorrect stylesheets. 

I will be moving away from the current design where the epub's CSS / Stylesheet is used for rendering the content and go towards a design where all books will be rendered based on a Bookworm specific stylesheet. (Issue #273)

Closing this issue based on the above two reasons.
