### ISSUE TITLE
Table of Contents do not work for Anchors on pages

### ISSUE THREAD

**Issue by keeferrourke** [babluboy/bookworm#154]
Using Bookworm 0.9.1 installed from Flathub, some books do not appear to split pages, sections, or chapters properly. Using the progress slider, instead of jumping to the next page as I expected, the reader jumped past all the chapters in the book, and went straight to the "About the Author" at the end of book. Attached are screenshots demonstrating the issue.

The title page and copyright info are their own pages, however every chapter appears to be mashed into a single page, making this book pretty well unreadable.

The first few pages are expected...:
![image](https://user-images.githubusercontent.com/6888381/33243945-b3bf76c0-d2bc-11e7-94b9-97db87fb5302.png)
![image](https://user-images.githubusercontent.com/6888381/33243917-62a44cde-d2bc-11e7-9c9a-7106e240c4f0.png)
![image](https://user-images.githubusercontent.com/6888381/33243921-72d219b0-d2bc-11e7-88c4-965cab271305.png)

If it's not clear in the screenshot, the entire book's content (all chapters) are mushed into this extremely long single-page view.
![image](https://user-images.githubusercontent.com/6888381/33243964-246bdc9c-d2bd-11e7-94b7-0c8e01a5d99a.png)

The next page (last page in the book):
![image](https://user-images.githubusercontent.com/6888381/33243939-a0b32a4a-d2bc-11e7-9292-0058835ab2f9.png)

I am not certain of the legality of redistributing this book (I don't see why I shouldn't be allowed to, but alas copyright lawyers are not a force to contend with), so I won't post it here, but if it's helpful to debug, I may be able to email it to you @babluboy. Let me know.

**Comment by babluboy** [comment]
@keeferrourke Is this book a ePub or a PDF ? If its a PDF then I'm using pdftohtml utility to extract the pages from the PDF in HTML. However if this is a ePub then the splitting is done based on the content of the toc.ncx file in the ePub. You can unzip the ePub and look at the toc.ncx in the root folder...

I have plans to make the pages fixed width in the future which would anyways solve this issue of long chapters. But lets see if this is due to a issue in the code for splitting the chapters or due to the book's chapter defined in the way that it is being displayed.

Happy to receive the ebook on my email bablu.boy@gmail.com to investigate further.

**Comment by keeferrourke** [comment]
Oops, forgot to mention: it's an ePub :)
I'll forward the file to you tonight!

**Comment by babluboy** [comment]
@keeferrourke can you send me the ePub where you are seeing this issue. Will be good to add a fix if required

**Comment by keeferrourke** [comment]
@babluboy so sorry, I forgot. Sending you the file now. :)

**Comment by babluboy** [comment]
I have got the issue after inspecting the epub contents, looking at the toc.ncx of the ePub, it has the chapters as part of the same html page i.e. `content src="ch01.html#multi-threaded-programming"`, `content src="ch01.html#creating-threads"`, etc instead of separate pages.

The current code will only show as many pages as there are individual html files inside the epub which is why one big page covering all the chapters is coming up during the navigation. The links on the table of contents also does not work for the bookmarks and jump to the big page for all the chapters.

I will check to see if any improvement can be done to handle bookmarks so that the navigation from the table of contents jumps to the right section/position of the page. However, the pagination by a fixed number of lines or characters (which will be required to split big pages) is a future piece of work.

**Comment by babluboy** [comment]
@keeferrourke Pushed changes to fix this issue. Now Table of Contents with anchors should jump to the right position of the page where the anchor is located.

Will be great if you can test either from the daily PPA or by building from the GH source code on master
Please re-open this issue if you still find problems.
