### ISSUE TITLE
Incorrect table of contents for some books in ePub format

### ISSUE THREAD

**Issue by sxc731** [babluboy/bookworm#160]
All the epub books I have from Packt (https://www.packtpub.com) show the ToC as "Content #1, Content #2, etc...".  
Other eBook readers I use (https://www.epubread.com/en/, a Firefox add-on, and and iBooks on my iPad) show a regular ToC, which is certainly more usable (see screenshots).

This is on Ubuntu 17.04 x64 but I don't suppose the OS makes a difference here?

Thank you for Bookworm.  It looks like it could replace the Firefox add-on if this issue was fixed...

PS: if you need a sample to test it, PackPub is currently running a $5 offer on all eBooks ;-), which I'm happy to fund if you let me know how to...  The offer ends pretty soon though so need to hurry (no expectation that the bug will be fixed before the offer ends ;-)

![instant vert x_064](https://user-images.githubusercontent.com/10687710/34485406-c415af28-efca-11e7-8529-ac3012cccdb1.png)
![instant vert x - anonymous - mozilla firefox_065](https://user-images.githubusercontent.com/10687710/34485463-25d6087a-efcb-11e7-95ee-0b3f0e7a5e7b.png)

**Comment by babluboy** [comment]
@sxc731 many thanks for your interest in bookworm and raising this issue. I'm currently on vacation and have no access to my machine to test this....but will use this issue to track this.

Couple of things...looks like you are using the older version of bookworm....I did some work on the latest version which I pushed to AppCenter before taking off on vacation...although I am not sure if this issue is fixed by some of the changes I did on the last version...will push the latest version to the PPA after I figure out how to reverse the RDNN changes I did for pushing into AppCenter.....

Secondly any chance you can send me a an ebook from the website...that way I can readily take a look at it when I return back next week....if that's going to violate copyright then can you unzip the ePub with zip and send me the .ncx or .toc file which should be present in the data folder...

**Comment by sxc731** [comment]
Hi there @babluboy, thank you for the quick reply!  

It looks like I'm using the latest version available on the PPA, which is reported as `0.6-0~42~ubuntu17.04.1`; however the "about" dialog reports "0.9.1".  I tried to follow your instructions to build from source but unfortunately failed at the first step:
```
$ sudo apt build-dep granite-demo 
Picking 'granite' as source package instead of 'granite-demo'
E: Unable to find a source package for granite-demo
```
In terms of testing this issue, I found the 'donate' button on your github page and transferred in £15.  This should be enough to buy an interesting book of your choosing from Packt (as mentioned, they have an "all eBooks for $5 discount on at the moment; not sure how much longer - the website says "ends soon...") I have 6 eBooks from them and they all behave the same.  https://www.packtpub.com/virtualization-and-cloud/openstack-architects is one that demonstrates the issue .  But do let me know if you'd rather I sent you the unzipped content.

**Comment by babluboy** [comment]
@sxc731 Many thanks for the generous donation....should be enough to get me a ebook when i'm back next week...however to be on the safe side you can send me the unzipped content....

Please have a look at issue #159 to resolve the dependency issue of building from source....

**Comment by sxc731** [comment]
Hi @babluboy, I have attempted to follow #159; the issue is Ubuntu 17.04 only appears to have `libgranite2` instead of `libgranite3`.  The compilation thus fails with:
```
dialog.vala:375.26-375.46: error: The name `Toast' does not exist in the context of `Granite.Widgets'
```
Could this be related to why [people appear to be having trouble installing Bookworm on 16.04](https://askubuntu.com/questions/947843/bookworm-installation-fails-with-unmet-dependencies-error)?

The above link allowed me to discover the existence of your `bookworm-daily` PPA so I installed the version that came out of there (`0.6-0~141~ubuntu17.04.1` => 0.9.2 in UI); the table of contents issue persists.

In any case, here's the TOC extracted from one such eBook as you requested.  Enjoy the rest of your holiday!

[toc.zip](https://github.com/babluboy/bookworm/files/1601420/toc.zip)

**Comment by babluboy** [comment]
@sxc731 I downloaded the Open Stack for Architects eBook and opened it on elementary OS Loki (Ubuntu 16.04.3 LTS) and the ToC shows up fine as per the screen shot below. Maybe the changes I might have done on the latest version (available only for elementary OS currently).

I am now building the latest code on Launchpad Daily PPA (the executable will be com.github.babluboy.bookworm instead of bookworm). This change was mandated by elementary OS app standards. I will update this issue when the build is complete with the commands to install. You might have to un-install your current bookworm application and install the latest one.

I will add an update when the [ppa](https://code.launchpad.net/~bablu-boy/+archive/ubuntu/bookworm-daily/+recipebuild/1513916) is built for Zesty (Ubuntu 17.04).

**Comment by babluboy** [comment]
@sxc731 Looks like it will take a while to have the PPA updated - at the moment there is a Launchpad [issue](https://twitter.com/launchpadstatus/status/948688233029881856) with no ETA which is blocking the build of code.

If you are fine, then you can give the latest version of Bookworm a try on Flatpak. Here are the instructions:
First install flatpak using these commands:
```
sudo add-apt-repository ppa:alexlarsson/flatpak
sudo apt update
sudo apt install flatpak
```

Then install Bookworm with this command:
` flatpak install --from https://flathub.org/repo/appstream/com.github.babluboy.bookworm.flatpakref`

**Comment by babluboy** [comment]
Forgot to mention, please remove the current bookworm installed via PPA before installing via flatpak...

**Comment by babluboy** [comment]
Downloaded "Mastering Blockchain" from Packt and the ToC opens fine as well...closing this issue, please don't hesitate if you see the issue persists.

![packt toc](https://user-images.githubusercontent.com/14061478/35151593-d5ba0d24-fd16-11e7-8344-760d92e27e96.png)
![packt books](https://user-images.githubusercontent.com/14061478/35151605-e2fef0da-fd16-11e7-90e2-31d6a53e933e.png)

**Comment by sxc731** [comment]
Hello @babluboy and thank you for the updates!

I recently had to upgrade my laptop to Ubuntu Artful (clean install) due to Zesty being made EOL.  So I just re-installed Bookworm from the stable PPA as you recommended (had to tweak the Elementary PPA as it only supports LTS so I used the Xenial version, which seems to have worked fine).

So the good news is that Bookworm works fine on Ubuntu Artful; the bad news is... that this bug persists in exactly the same form! (only but consistently all Packt ePub e-books).

Version info:
* APT: `0.6-0~201801121751~ubuntu17.10.1`
* About dialog says: `0.9.5`

Is there perhaps a way I could debug the issue since you don't seem to be able to reproduce it?

**Comment by babluboy** [comment]
@sxc731 Thanks for the feedback. This is interesting. Looking at the code the "Chapter 1" kind of default is done only when the TOC cannot be parsed from the ePub. Can you try the following and pipe the debug into a file and attach it here:
1- execute bookworm in debug mode by running the following com.github.babluboy.bookworm --debug > ~/bookworm_debug.txt
2- check the TOC of a Packt book
3- remove the Packt book from the library and re-add it back again from the ePub file
4- visit the ToC of the book just added

This should add debug about how the book ToC is being parsed. Please attach the debug file here when you are done. The interesting bit is data like the following:
`### Book MetaData details fetched from DB: id=179,BOOK_TOC_DATA=/home/sid/.config/bookworm/books/Openstack for Architects by Solberg Michael & Silverman Ben.epub/text/part0003.html~~##~~OpenStack for Architects~~^^~~/home/sid/.config/bookworm/books/Openstack for Architects by Solberg Michael & Silverman Ben.epub/text/part0004.html~~##~~Credits~~^^~~`

Thanks for working with me on this issue, might be a subtle bug

**Comment by babluboy** [comment]
I think I have got the issue - when I compared the ncx you had sent and the ncx from the book i was testing with, the xml tags for navpoint has a prefix - this is causing the parsing to fail.

ncx section from your file:
```
 <ncx:navPoint id="id286691991" playOrder="3">
        <ncx:navLabel>
          <ncx:text>Credits</ncx:text>
        </ncx:navLabel>
        <ncx:content src="pr02.html"/>
 </ncx:navPoint>
```
ncx section from the samples I was testing:
```
 <navPoint class="chapter" id="num_4" playOrder="4">
      <navLabel>
        <text>About the Reviewer</text>
      </navLabel>
      <content src="text/part0006.html"/>
  </navPoint>
```

Not sure why the samples I got had the expected format while the ones you got were different. But will try and make the code generic enough to work for both.

**Comment by sxc731** [comment]
Hi @babluboy, looks like you've nailed it!

It seems likely my TOCs have those "prefixes" (actually [XML namespace](https://en.wikipedia.org/wiki/XML_namespace) markers) whereas yours don't because a different library (or version thereof) is involved in producing these TOCs on my OS compared to yours (since we have some of the exact same books).

XML namespaces are perfectly legit XML syntax and they _should_ be understood by any good XML parser (how about [this one](https://birdfont.org/xmlbird.php)?); your code shouldn't even have to deal with that in theory.  

That said, I wouldn't mind a quick fix to the issue before you embark on that kind of re-factoring - I know, I'm greedy ;-)

**Comment by babluboy** [comment]
@sxc731 Completely agree with you - namespaces should be handled correctly as valid XML. I had plans to replace the current string based parsing of the XML content (like the ncx files) with a proper XML parser library. Opened Issue #169 to track this.

However, a quick fix seems possible, let me see if I can hack something today.

**Comment by babluboy** [comment]
@sxc731 Just pushed some code replacing the ToC string parsing with libxml and as expected the parsing works correctly for both XML with namespaces and no namespaces. The code changes should be picked up on Launchpad by the daily PPA tonight.

If you are happy to check, then I will provide the instructions to get bookworm from the daily PPA and test with the Packt Books you have got.

**Comment by sxc731** [comment]
Hi @babluboy, I just upgraded as you suggested (`0.6-0~201801222245~ubuntu17.10.1`, GUI says v 1.0.0. At first it looked like the issue persisted but then I thought I might try to refresh the cache (deleted `.config/bookworm` and ran `com.github.babluboy.bookworm --discover`) and now the TOCs of all my books appear to be parsed correctly (tried a sample across many publishers).

There is another issue that's apparent when running `bookworm --discover` (a number of my books are rejected).  This appears unrelated as it was already occurring before this last change.  I'll raise another ticket to cover that.

**Comment by babluboy** [comment]
@sxc731 Many thanks for the testing. Yes, I forgot to mention that books already in the library have their ToC cached and will not take advantage of the new code...while deleting the cache and doing a discovery is a way to get the ToC getting regenerated, it will erase all the work like tagging, annotation, meta data updates (author, title, etc)...so I feel a better way could have been if I had a process like discovery to go through all the books in the library and re-generate the ToC into the cache...however the flip side is that the original ePub file might have been removed by the user from its location after it was imported into Bookworm...anyways, ToC is not a major show stopper and I will keep it the way it is now - only new books added to the library will take advantage of the xml parser. Hopefully not many books have the namespace in the ncx xml and hence will not be impacted by this issue....

Will watch out for the other issue you have mentioned, if the impacted books can be shared it will help, otherwise we can try debugging...
