### ISSUE TITLE
Use unar instead of unrar

### ISSUE THREAD

**Issue by grvrulz** [babluboy/bookworm#161]
The `unrar` package that Bookworm depends on is non-free. There has been a free alternative to unrar available in the repos of major distributions for some time, called 'The Unarchiver'. It provides two utilities called `unar` and `lsar` which can be used to extract and list files from rar archives.

Bookworm should depend on the free unar package instead of unrar, or make the dependency on unrar optional.

Unarchiver website: 
https://theunarchiver.com/command-line

Launchpad: https://launchpad.net/ubuntu/+source/unar/

**Comment by babluboy** [comment]
Thanks for this - I was not aware that unrar is non-free. Will check out unarchiver and see if it can extract mobi package, or better still I should be using a API rather than depend on an executable.

**Comment by babluboy** [comment]
Replaced UNRAR with UNAR and it works quite well with CBR files which is the archive that I decompress with UNRAR...From my quick check it looks like UNAR has support on a number of different distros...hopefully once I confirm that it is working well on other distros then I might replace the UNZIP (for CBZ files) with UNAR as well....

**Comment by caronc** [comment]
Hey guys; how did this fair out when you did this change? Has unar been reliable for you? Any regrets swapping it out? I'm not using this specific product, but am faced with a similar situation of considering an alternative to unrar for licensing issues.

**Comment by babluboy** [comment]
@caronc Hi. Yes, unar works quite well and I have replaced my unzip with unar as well. 

However I am thinking of using the vala archive library to do my decompressions. That way I'm more in control programatically and there is no need for users to install a separate binary for use with my program. Also forking out to use binaries are a hassle when you want to containerise your app or make it cross distro (not speaking about unar, but in general binaries are used differently in different distros i.e. fedora)

So if you are switching, you may want to consider using a programatic way to decompress archives rather than depend on a separate binary.
