### ISSUE TITLE
Allow for true 'night mode' ; that is true black background with white text.

### ISSUE THREAD

**Issue by arooni** [babluboy/bookworm#164]
I tend to practice my guitar at night, it would be nice to have a truly night mode.. though I guess some of that text is black and won't appear well with a black background.  calibre book reader gets around this by letting you open image files in a separate window.

![screenshot from 2018-01-16 18-48-08](https://user-images.githubusercontent.com/556667/35019779-5559ff10-faee-11e7-95d1-5c814055dabb.png)
![screenshot from 2018-01-16 18-47-47](https://user-images.githubusercontent.com/556667/35019780-5576cb72-faee-11e7-9d82-bec1b0956b36.png)

**Comment by babluboy** [comment]
@arooni I have provided a customization to the three color profiles in the preferences dialog. You can customize profile 3 (the dark profile) and set the text to black instead of the default grey color that I ship with. You can set the background color as well.
Let me know if this helps.
![customize profile](https://user-images.githubusercontent.com/14061478/35040469-0fa22818-fb79-11e7-90f5-05d745912618.png)

**Comment by babluboy** [comment]
Please re-open if the above work around is not working as expected
