### ISSUE TITLE
Text overflows off book cover

### ISSUE THREAD

**Issue by TraumaD** [babluboy/bookworm#167]
Text should wrap if it exceeds the book cover. (probably a little sooner for padding)
![overflowing-text](https://user-images.githubusercontent.com/10608836/35083233-bb6f20b4-fbe3-11e7-877d-22423a737708.png)

**Comment by babluboy** [comment]
Thanks for this issue - I had seen it earlier but not able to replicate it now. Any chance you can pass me the ebook above which causes this issue.
I have set the wrapping for the title, but not sure if it is not working under some condition.

**Comment by TraumaD** [comment]
I believe the problem happens when there is no spaces in the title and there for no definite place for the text to break. the ebook I was using is just a pdf
[pythonforkids_1490905401.pdf](https://github.com/babluboy/bookworm/files/1643795/pythonforkids_1490905401.pdf)

**Comment by babluboy** [comment]
Thanks for the pdf, I have replicated the issue. Tried some ways to have the wraping of text on the label by setting wrap, max chars, etc. but didn't work. I will now try the blunt method of adding a space after a certain amount of chars in the title - that will make the wrapping work

**Comment by babluboy** [comment]
@TraumaD Added a fix to handle long titles and introduce spaces to allow wrapping within the cover boundary. Please re-open this if you find the fix is not working correctly. The only issue is that the space is introduced after every 18 chars which might be in the middle of a word.

![title wrap](https://user-images.githubusercontent.com/14061478/35162709-11c8e194-fd3c-11e7-93bc-41b7f6dedab2.png)
.
