### ISSUE TITLE
Bookworm runs in the background after closing it

### ISSUE THREAD

**Issue by xayden** [babluboy/bookworm#179]
Bookworm runs `pdftohtml` in the back ground, even after closing it knowing that I didn't open any book!

**Comment by babluboy** [comment]
@xayden Bookworm runs a background process to discover and add books to the library if a watch folder is set up. If the watched folder contains a PDF which is not there in the library then pdftohtml will be running as part of the parsing of the PDF. Once all books in the watched folder are added to the library then you should no longer see these background processes. 

If you would not like to see these background processes, then remove all folders from the watched folder drop down in the preferences.

Let me know if this resolves your question.
![screenshot from 2018-03-06 19 24 42](https://user-images.githubusercontent.com/14061478/37053601-7956f89e-2174-11e8-97ef-fbb0d2b1bdd7.png)

**Comment by kousu** [comment]
I wonder if I was seeing this behaviour too, even without any scan folders defined, in #177.

**Comment by babluboy** [comment]
Will be good to know if the background tasks for Bookworm is found without any scan folders....I can then check the code to see if there is a bug...

**Comment by JonasT** [comment]
@babluboy it is not super intuitive / obvious that watched folders will lead to the program running forever. I suggest there should be a separate option "keep running in background for continuous scan", and otherwise the scanning should be limited to when its running - I think it's reasonable if it was enabled by default, but then it would also be obvious what is going on with a single look into the preferences, while I don't think it is obvious right now.

(bookworm, if not in the background, could re-scan the folders as a whole to catch up after a restart after all, so there is no real *need* to stay running forever just to be able to scan folders. It could lead to some discovery delays of course, but that is why the background option could be enabled by default)

**Comment by babluboy** [comment]
@JonasT Hi, Bookworm runs the scan on the watched folders after the window is closed and exits the process if there are no further valid ebooks to add to the library. 

There is no forever option to scan for books - let me know what made you think so. Maybe when I wrote "background process" it indicated something like a daemon process and caused the confusion. My bad there. 

Obviously the first run is a long one if there are a lot of books to add.But then there is no continuous process running in the background looking for new books to add - if a new book is added then the process will find it when bookworm is opened by the user and then subsequently closed which will run the discovery process again to search for new books within the watched folder.

Closing this issue as there is no thought to run daemon processes for bookworm at the moment.
