### ISSUE TITLE
'Check Word Meaning' option not implemented

### ISSUE THREAD

**Issue by joebonrichie** [babluboy/bookworm#185]
The check word meaning should not exposed to the user as an option as it is not yet implemented
https://github.com/babluboy/bookworm/blob/master/src/window.vala#L362

This was noticed when packaging the application for Solus as you can see in the discussion [here](https://dev.solus-project.com/D2562), it creates confusion for the user and even for maintainers who'd rather not dig into the code all the time.

Until it is implemented I would recommend hiding the setting from the user,

Thanks in advance!

**Comment by babluboy** [comment]
@joebonrichie Many thanks for logging this issue. Somehow during the last release the Word Meaning option became available by mistake. I will either complete this function in the next release or hide it from the user until it is fixed.

**Comment by babluboy** [comment]
Settled on "dict" as the mostly widely available cross distro dictionary. However most people will have Internet access and can use an online dictionary rather than installing an off-line one.

So as the first implementation I have externalized the dictionary in a script in the user's home directory. The script will default to an online search on "http://wordnetweb.princeton.edu/perl/webwn" but the user can easily comment out the online section and enable the offline section which uses "dict". Hopefully this works best and makes the functionality configurable. Will add a link on the dictionary results view to the script to make it easy to bring up and edit.

![dictionary](https://user-images.githubusercontent.com/14061478/43037755-351473e0-8d09-11e8-98d7-0ea7d020db9d.gif)

**Comment by x-ji** [comment]
Is there any documentation of this feature? Doesn't seem to be in either the README file or the Github Pages page.

**Comment by babluboy** [comment]
> Is there any documentation of this feature? Doesn't seem to be in either the README file or the Github Pages page. I sometimes read books in other languages and would need lookups of words in those languages.

Thanks for pointing this out. I will add it to the Bookworm website which is mentioned in the Readme for checking out features

**Comment by babluboy** [comment]
Instructions for changing the dictionary source:
1- Use dictionary offline: Edit the file /usr/share/com.github.babluboy.bookworm.dictionary.sh and comment out the lines [15](https://github.com/babluboy/bookworm/blob/2dfab307b1f751f98fd41a1932d2f190822ba9da/data/scripts/com.github.babluboy.bookworm.dictionary.sh#L15) to [21](https://github.com/babluboy/bookworm/blob/2dfab307b1f751f98fd41a1932d2f190822ba9da/data/scripts/com.github.babluboy.bookworm.dictionary.sh#L21) and uncomment line [27](https://github.com/babluboy/bookworm/blob/2dfab307b1f751f98fd41a1932d2f190822ba9da/data/scripts/com.github.babluboy.bookworm.dictionary.sh#L27)

2- Use a different dictionary: Edit the file /usr/share/com.github.babluboy.bookworm.dictionary.sh and change lines [16](https://github.com/babluboy/bookworm/blob/2dfab307b1f751f98fd41a1932d2f190822ba9da/data/scripts/com.github.babluboy.bookworm.dictionary.sh#L16) and [18](https://github.com/babluboy/bookworm/blob/2dfab307b1f751f98fd41a1932d2f190822ba9da/data/scripts/com.github.babluboy.bookworm.dictionary.sh#L18) to grab data from an online dictionary of your choice

**Comment by babluboy** [comment]
@x-ji Did you manage to change the online dictionary? Did you install dict? Will be good to know the changes you made in the dictionary script
