### ISSUE TITLE
Dark mode highlighting makes text unreadable

### ISSUE THREAD

**Issue by memeplex** [babluboy/bookworm#202]
The bright default color is not only awful in dark mode but also makes the highlighted text unreadable because of lack of contrast. I can't find any way to change the highlighting color, must be part of the profile.

![image](https://user-images.githubusercontent.com/2845433/41502935-4a87d0f6-719c-11e8-9539-d378cedc932d.png)

**Comment by memeplex** [comment]
Btw, having the screenshot at hand, are the ones at the left stock icons? The info icon looks a bit blurred, is it a png?

**Comment by babluboy** [comment]
@memeplex  Thanks for raising this, the highlighted text is indeed hard to read in dark mode.
Since the highlight colour is part of the profile color scheme, I will add it to the customize profile option in preference. At the moment the background and foreground colours are there as part of customization, will add highlight as well.
![screenshot from 2018-06-19 07 30 20](https://user-images.githubusercontent.com/14061478/41580454-da2499cc-7392-11e8-9af5-a856c3a0242e.png)

**Comment by memeplex** [comment]
Great! Thanks!

**Comment by babluboy** [comment]
Made changes to add highlight color as part of the profile customization and also made the default highlight color bluish for the dark mode which is hopefully more readable than the yellow. The user can now configure the highlight color for all three profiles using the preference menu.

![screenshot from 2018-06-24 22 32 50](https://user-images.githubusercontent.com/14061478/41824152-991bf2ca-7803-11e8-95b6-5038af454239.png)
