### ISSUE TITLE
Feature request: Allow minus button in UI to immediately remove selected book in list view

### ISSUE THREAD

**Issue by edward-shen** [babluboy/bookworm#209]
Currently, to remove a book in the list view, you need to select the checkmark, select the book(s) you wish to remove, and then press the remove button. If the book is selected on the list (but not selected via the checkmark feature), pressing the remove button does nothing.

For reference, here is what I mean by a book being selected by the list view, but not by the selection tool:

![example](https://user-images.githubusercontent.com/6173958/43242289-2b1172ae-906e-11e8-993c-6ca42719fb34.png)

I'm not familiar with the workflow of Elementary OS, but if possible, I'd like the remove button either hidden away or grayed out before selecting a book using the selection tool in list view, or allowing a book to be immediately removed if it's selected on the list. I personally found it counter-intuitive that I had to select an already selected book to remove a book on the the list view.

**Comment by babluboy** [comment]
@edward-shen Thanks for your interest in Bookworm. Agree with your thoughts that selection should be sufficient to remove the book - Elementary Files follows that workflow.

I just kept the same logic for the grid view and the list view to select by check mark to remove from library - because there is no selection in grid view and single right click opens the book.

Maybe couple of things to improve:
1. Don’t show the remove (-) button unless one or more books are selected or checked. 
2. Mouse over help text on disabled remove button should mention selection requirement for deletion
3. In list view single selection should enable the remove button but check mark will be required for multiple selections

Does the above sound like a good workflow?

**Comment by edward-shen** [comment]
At least for the list view, I think disabling the remove icon would be preferable to hiding it and showing it all the time. After all, the user will always be selecting a book in the list view, regardless of whether or not they want to delete it. Perhaps just graying out the button for both views will be better, and then implementing points 2 and 3?

But yeah, otherwise that sounds like a much better workflow.

Thanks again for making a lightweight epub reader!

**Comment by babluboy** [comment]
@edward-shen Agree. I intended to disable the button rather than hide it. Displaying a greyed-out (disabled) button is always better than not showing it - makes it apparent to the user that the functionality is present.

I see many opportunities to make Bookworm more lightweight and faster...will improve it over time. Several issues are open for performance enhancement. At the moment my key focus is to add capability for pagination than showing the whole chapter.

**Comment by babluboy** [comment]
Implemented the following:
1- Don’t show the remove (-) button unless one or more books are selected or checked.
2- Mouse over help text on disabled remove button should mention selection requirement for deletion

To-Do:
3- In list view single selection should enable the remove button (check mark will be required for multiple selections)

**Comment by babluboy** [comment]
On hindsight (3) above will be inconsistent for the following reasons:
1- Doing the removal if a single book is selected on the list view will make it inconsistent with the grid view
2- When the books are being selected via the checkmark for removal then only one book will be in selection mode while all the others will have the check mark enabled against them and all will be removed, not just the selected one.

In view of the above, closing the issue as (1) and (2) have been implemented.
