### ISSUE TITLE
FB2 Format 

### ISSUE THREAD

**Issue by ItsPossibleAlready** [babluboy/bookworm#215]
Can you add FB2 format. Most books for computer wrote to pdf or fb2.

**Comment by babluboy** [comment]
@ItsPossibleAlready Thanks for your interest in Bookworm - I will use this issue to remind myself on the FB2 format and FB2 support

**Comment by smaragdus** [comment]
I second support for **FictionBook** (**FB2**) format.

**Comment by babluboy** [comment]
I had a look and the FB2 format looks like it packs the entire ebook content into a single file - if I go by the current Bookworm architecture the entire book will be presented as a single chapter. Looks like I have to implement pagination (#170) as a must have for FB2

**Comment by babluboy** [comment]
Since I'm still not being able to do pagination properly, I thought why not go ahead and implement the support for FB2 :-)
Just pushed some initial changes which allows Bookworm to read FB2 and show the extracted contents in a single page. Need to work out the image extraction from the base64 coded text in the FB2 file. 

Appreciate if anyone can build from source to test this and see if the text and meta data extraction (author, title) is working for FB2 - I downloaded a few and it works for those. Will need to test more on possible variations of the FB2 formats.

**Comment by babluboy** [comment]
Code for Image extraction for cover image is completed. The only thing left is to extract additional meta data present (apart from author and title) like genre and add them to the book's tag's to make it easier to search the book.

**Comment by babluboy** [comment]
Added support for .FB2.ZIP as many of the FB2 files are zipped for compression. While it would have been possible to let the user do the unzip and add the .FB2 file to Bookworm but looks like the norm is to support .FB2 and .FB2.ZIP - so aligned Bookworm for the same.
