### ISSUE TITLE
Publish in Juno

### ISSUE THREAD

**Issue by danrabbit** [babluboy/bookworm#217]
Our [second Juno Developer Preview](https://medium.com/elementaryos/developer-preview-juno-beta-2-is-out-418f5037e9bb) is out and Juno's big debut is just around the corner! We'd love to see your app in AppCenter on release day.

Check out this [Developer Tips](https://medium.com/elementaryos/developer-tips-updating-your-apps-for-juno-453c07a5b3a7) article to learn how to publish your app for elementary OS 5.

If you need help updating your app for Juno, we’re always standing by in [Gitter](https://gitter.im/elementary/houston) and the [Community Slack](https://join.slack.com/t/elementarycommunity/shared_invite/enQtMzU1NDU4OTE1MjY2LWUyOTBkZGNkZGM4MDgzZjE2ZjRiZDgwMDQ1ZTA0MzcxYjI0MDUyNGRlNDI5ZWViNDkwMzMwYzczMDY2ZjA0MTc) to help wherever we can.

**Comment by babluboy** [comment]
Many thanks for the reminder...completely forgot about making a release for Juno ...will do when I return home tommorow...

**Comment by babluboy** [comment]
Published for Juno and Loki (via deb packaging branch)

**Comment by babluboy** [comment]
@danrabbit Reopening this one :-( as I realised that the webkit bug in bionic is not allowing Bookworm to build for Bionic (Juno). I guess I will have to sit it out until the bug is resolved - saw that a few other apps like Odeyssey which use webkit have the same issue.

If there are any known workarounds for publishing webkit dependent apps on Juno, please let me know

[https://bugs.launchpad.net/ubuntu/+source/webkit2gtk/+bug/1795901](https://bugs.launchpad.net/ubuntu/+source/webkit2gtk/+bug/1795901)

**Comment by danrabbit** [comment]
Yeah sorry, sounds like we're waiting on the upstream fix as well :/

**Comment by babluboy** [comment]
All good on the WebKit issue. WebKit bug fixed upstream and Bookworm is available on Juno
