### ISSUE TITLE
Mobi files aren't loading

### ISSUE THREAD

**Issue by martimallow** [babluboy/bookworm#230]
Everytime i try it shows this 
![image](https://user-images.githubusercontent.com/28545271/50555060-194f9700-0cae-11e9-9099-0f8b300d34d7.png)

**Comment by babluboy** [comment]
@martimallow  Thanks for raising this issue. Looks like Bookworm is not able to parse the mobi file. Can you please do the following and provide me the data:

1. Open terminal and run the command: com.github.babluboy.bookworm —debug > ~/bookworm.txt
Then try opening the mobi file in Bookworm and after you get the error close Bookworm. In your home directory find the file bookworm.txt, attach the file to this issue.

2. Attach the mobi file to this issue here so I can also try and replicate the issue.

**Comment by martimallow** [comment]
Hey, thanks for answering. I'm not sure if the command you sent should be done in one line.  I think i made a mistake cuz after run the command, got this
![image](https://user-images.githubusercontent.com/28545271/50566571-84d34c00-0d22-11e9-83fc-ef2b8257352a.png)

But following the steps here what i got.
[bookworm.txt](https://github.com/babluboy/bookworm/files/2718833/bookworm.txt)
[Como morrem os pobres e outros - George Orwell.txt](https://github.com/babluboy/bookworm/files/2718836/Como.morrem.os.pobres.e.outros.-.George.Orwell.txt)
Ps. I just change the name extension to txt so i could upload, original name: "Como morrem os pobres e outros - George Orwell.mobi"

**Comment by martimallow** [comment]
https://drive.google.com/file/d/1PrcjoMU92Te0btH6A33shTJyHTEOWg0R/view

**Comment by babluboy** [comment]
Thanks for providing the info, the ebook you have shared opens fine on my eOS - so there is no problem with the ebook itself.

Looking at the debug file you have attached, I see the error - Falha ao executar processo filho “/usr/share/bookworm/scripts/mobi_lib/mobi_unpack.py” (Arquivo ou diretório inexistente)

It looks like you have an older version of bookworm, can you please remove and re-install from AppCenter. Instead of the /usr/share/bookworm/scripts/mobi_lib/mobi_unpack.py directory the correct structure should be /usr/share/com.github.babluboy.bookworm/scripts/mobi_lib

Let me know after you remove and re-install bookworm and if the problem still exists
