### ISSUE TITLE
feature request: sort by most recently opened

### ISSUE THREAD

**Issue by arooni** [babluboy/bookworm#255]
love the app, would be nice to have my most recently viewed ebooks at the top of the list

**Comment by babluboy** [comment]
@arooni Yes that should be the default way to populate the library. Are you not seeing this in the list mode or in the book thumbnail mode? try opening some books at the bottom and close bookworm and reopen it to see if thy appear on the top.

Linking it to #232 so that I remember to do this when I do a paginated library.

**Comment by babluboy** [comment]
Closing this one as the most recently read books appear on top when bookworm is closed and opened after reading the book(s). The sorting will not happen before bookworm is closed and restarted.
