### ISSUE TITLE
make progress bar optional

### ISSUE THREAD

**Issue by aeosynth** [babluboy/bookworm#269]
the progress bar takes up a lot of space and is a kind of spoiler, I'd like an option to disable it

**Comment by babluboy** [comment]
@aeosynth Thanks for raising this issue. Just that I have a better idea of the problem can you please post a screenshot of the progress bar?

On Elementary OS the progress bar on the hover of the book cover and the progress bar when books are being imported into the library are thin and unobtrusive, so will be interesting to see how it looks on your system

**Comment by aeosynth** [comment]
![bar](https://user-images.githubusercontent.com/75317/62831781-14a27800-bbd9-11e9-8a98-1cc163ea622a.png)

it takes up about 1/2 an inch of space at the bottom, and it's spoilery.

**Comment by babluboy** [comment]
Thanks for the screenshot - I can agree with the wastage of the space on the footer. Two suggestions:
1- Right click or do F11 to go into full screen mode to make max use of reading space.
2- What distro are you using ? On Elementary OS the footer is really thin and not as intrusive as yours. There must be a stylesheet for your distro where you can adjust the footer. accommodating different stylesheets will not be possible but there must be a way to use the elementary stylesheet which can give you the intended look and feel.

This is how the footer looks like in elementary os:
[https://github.com/babluboy/bookworm/blob/gh-pages/images/BookwormReadingView.png](https://github.com/babluboy/bookworm/blob/gh-pages/images/BookwormReadingView.png )

**Comment by babluboy** [comment]
The issue was the page number which was appearing on top of the slider making the width larger. I have put the page number on the right side which has now made the footer slimmer on the reading view and of the same size as that of the library view. Here are the before and after screen shots.

![Thick Footer](https://user-images.githubusercontent.com/14061478/62832739-085a0180-bc51-11e9-873c-473896fceb81.png)
![Slim Footer](https://user-images.githubusercontent.com/14061478/62832740-085a0180-bc51-11e9-9892-91427cff98a0.png)

**Comment by babluboy** [comment]
Closing this one - please re-open if there are further issues with the same.
You can get the latest code by building from GitHub
