### ISSUE TITLE
Table of Content need some padding.

### ISSUE THREAD

**Issue by choyan** [babluboy/bookworm#28]
Currently, it doesn't have any padding beside it. It needs some I think
![screenshot from 2017-03-10 04 11 40](https://cloud.githubusercontent.com/assets/1283240/23784228/fde3157c-058a-11e7-9b72-6a0819fbcdff.jpeg)

**Comment by babluboy** [comment]
@choyan good catch. This would have come due to another bug I fixed to remove borders so that the text looks flush ....should be easy to add the standard padding...probably the padding might be needed in other places as well...please update if you spot anything else....

Will fix this today and release....

**Comment by babluboy** [comment]
Done. Added the padding in today's code push
