### ISSUE TITLE
Can not install on Ubuntu 18.04

### ISSUE THREAD

**Issue by matjazmav** [babluboy/bookworm#292]
Can not install on Ubuntu 18.04, can you help me?

```
$ sudo add-apt-repository ppa:bookworm-team/bookworm
$ sudo apt update && sudo apt install bookworm
...
...
...
The following packages have unmet dependencies:
 bookworm : Depends: com.github.babluboy.bookworm but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

**Comment by omendezmorales** [comment]
Hi @matjazmav ,
I'm not sure you're following _exactly_ the [install instructions](https://babluboy.github.io/bookworm/#install)?  your package name above should say
`com.github.babluboy.bookworm`

plus, there are additional instructions in case you miss the libgranite packag, described in the same page.
I hope it helps.

**Comment by cyberjaguar** [comment]
Why is it not just simply called `bookworm` ??? This is what everybody would expect and I guess every second user runs into this. Why are you using `com.github.babluboy.bookworm` as a program name? This does not make sense at all. Please make it just `bookworm` - KISS! Thanks!

Also it would be great to remove that additional ppa dependency, but I understand that this generates some work - is there no way to avoid that in the first place?

**Comment by Mandroide** [comment]
I had that issue, and the problem was that it needed _libgranite5_. I fix it with the following solution:

```
sudo add-apt-repository ppa:philip.scott/spice-up-daily
sudo apt install libgranite5

```
**Source**: [https://news.ycombinator.com/item?id=19197859](url)

**Comment by babluboy** [comment]
the reason why the package name was changed from "bookworm" to "com.github.babluboy.bookworm" is due to the Reverse Domain Name Notation (RDNN) as described in the Elementary HIG: [https://elementary.io/docs/code/getting-started#the-desktop-file](https://elementary.io/docs/code/getting-started#the-desktop-file)

Closing this as hopefully the installation issue with libgranite should be resolved by the installation of the dependant libraries. This is also described here:
[https://babluboy.github.io/bookworm/#install](https://babluboy.github.io/bookworm/#install)
