### ISSUE TITLE
Use com.github.babluboy.bookworm as your IDs

### ISSUE THREAD

**Issue by Philip-Scott** [babluboy/bookworm#3]
You should use those names on all the fies (Images, .desktop, gsettings) you include with your app, or else AppCenter will yell at you when you try to push it ;) Also, you should create an appdata file :) 

See: 

https://github.com/Philip-Scott/Notes-up/issues/76
https://github.com/Philip-Scott/Notes-up/issues/75

For an example, you can see https://github.com/Philip-Scott/Spice-up as i've still haven't updated the notes app to use IDs :sweat_smile:

**Comment by babluboy** [comment]
Updated the desktop and schema files with the proposed id and added a "appdata" file as well.

**Comment by choyan** [comment]
Some problem occurs during execution. May be due to app ID related problem after yesterday's push. 
`[INFO 10:46:43.455517] Application.vala:155: Bookworm version: 0.2
[INFO 10:46:43.455573] Application.vala:157: Kernel version: 4.4.0-64-generic
[ERROR 10:46:43.502920] [GLib-GIO] Settings schema 'org.bookworm' is not installed
[1]    7311 trace trap (core dumped)  bookworm`

I tried to both install as PPA and build from the source, but same problem.
