### ISSUE TITLE
Screenshot uses non-default window buttons placement

### ISSUE THREAD

**Issue by danrabbit** [babluboy/bookworm#55]
The screenshot for AppCenter should use the default window button placement. Less experienced users might be mislead that Bookworm will use a window button placement that doesn't fit in with their installation

**Comment by babluboy** [comment]
@danrabbit Thanks Dan, good point. I have updated the screen shots and the screenshot link is now showing the updated screenshot...however, Appcenter is still showing the older one - I guess that might be due to the cache. Will close this issue when I see the latest screen shot on Appcenter.
Feel free to comment or open issues - makes the app better and more usable
![bookwormlibraryview](https://raw.githubusercontent.com/babluboy/bookworm/master/screenshots/BookwormLibraryView.jpeg)

**Comment by danrabbit** [comment]
Screenshots are uploaded with your releases, so it'll be updated with your next release :)
