### ISSUE TITLE
Font chooser widget for Reading Prefference

### ISSUE THREAD

**Issue by babluboy** [babluboy/bookworm#62]
Kaloyan Genkov provided the following enhancement request on [this](https://plus.google.com/u/0/108373005915819607337/posts/SvSF4MbgRWj) Google Plus thread:

While using the default system fonts is a wise choice, the fonts used in books are different that those used in computer interfaces. In books they use serif fonts while the default font in elementary is a sans one. People suggest using Georgia for ebook body text: [http://rogerpacker.com/how-to-choose-typography-for-ebooks/](http://rogerpacker.com/how-to-choose-typography-for-ebooks/) The font choice is important since a good font can reduce the eye strain during long reading.

**Comment by uncertainquark** [comment]
Serif fonts are the standard for long reading. So there should be at least two options for this implementation:

1. Use default fonts from the ebook file
2. Default to Georgia instead of a Sans Serif font.

**Comment by babluboy** [comment]
@uncertainquark Thanks for the suggestions. PDFs dont have a font set, so I will default them to Georgia. The following are the serif choices I'm thinking of for the font options:
1- Georgia
2- Baskerville
3- Palatino
4- System - Chosen via Elementary Tweaks...Gives the chance to choose from a wide variety of sans, etc

Does that look like a good start ?

**Comment by uncertainquark** [comment]
Yes, that definitely sounds awesome and even feature complete I would say!

**Comment by m-delvalle** [comment]
From an accessibility point of view, a nice addition to that list would be 'OpenDyslexic' font.

https://opendyslexic.org/

**Comment by dar5hak** [comment]
I don't completely understand what you mean by system, but if it means relying on elementary Tweaks, it might not be a great idea, since not everyone has it installed, and moreover the HIG would recommend against that kind of configuration. You might want to just choose one serif font, and stick to it.

Also, Georgia, Baskerville and Palatino do not have an open source licence, if that is important to you. If you choose to only ship an open source font, you're looking for something like [Merriweather](https://fonts.google.com/specimen/Merriweather) or [Vollkorn](https://fonts.google.com/specimen/Vollkorn), and [Cinzel](https://fonts.google.com/specimen/Cinzel) for headings.

**Comment by babluboy** [comment]
@dar5hak yes, by system font i meant is set for use on the system - but you have a point in saying that if someone want to change the default droid, elementary tweaks need to be used.

Thanks for the licensing bit, I had not thought about it - if Georgia is on the system (it ships with eOS I guess) then will it be ok to use it without licensing it specifically ? perhaps not... [Vollkorn](https://fonts.google.com/specimen/Vollkorn) looks like a good serif to use...

**Comment by dar5hak** [comment]
Oh, now I see. If the OS ships with Droid and you're okay with Droid, that should be good. It would still work without Tweaks installed.

**Comment by babluboy** [comment]
Added the font chooser to the preference dialog
![font chooser](https://cloud.githubusercontent.com/assets/14061478/26561463/9fd398b0-44b6-11e7-8e93-f6b390f33e6d.png)
