### ISSUE TITLE
Bookworm abuses Contractor

### ISSUE THREAD

**Issue by matzipan** [babluboy/bookworm#71]
When I use Files, I right click in a random folder, the Bookworm contract is visible in my context menu. 

This feels to me like an abuse of Contractor. Entries for Bookworm should only be visible when a ebook filetype is right-clicked and the "Open with" menu is expanded.

**Comment by matzipan** [comment]
Anyway, nice work on the app!

**Comment by babluboy** [comment]
@matzipan good spot. I didn't realize I had got the mime type of "inode" in the contract which was responsible for showing Bookworm in the context menu for a folder right click. The fix was easy, just removed the "inode" from the contractor mime types and verified that Bookworm does not show in the context on folder right click...non ebook file types also dont show Bookworm in the right click menu...will push it into daily later tonight...
