### ISSUE TITLE
Add ability to import/set directories

### ISSUE THREAD

**Issue by yerbestpal** [babluboy/bookworm#74]
Calibre does a great job of organising my ebook library. It would be very useful if I could just import those folders rather than import each ebook from each individual directory.

**Comment by babluboy** [comment]
@yerbestpal Thanks for raising this - completely agree Bookworm should have a import mechanism.

There are a number of ways to get this done:
1- A preference item dialog where the user specifies the folder to import books - the import is done immediately like a do-it-now function
2- A preference item to allow bookworm to discover supported ebooks and add them to the library in the background and also allow the user to specify any folders which need to be skipped - the import is done in the background and books are added as and when they become available and not already available in bookworm

I kind of like the second option as it removes the requirement for the user to keep importing books once in a while.

**Comment by yerbestpal** [comment]
I prefer the second option also. So long as all the imported ebooks are copied to a specific library folder.

**Comment by babluboy** [comment]
@yerbestpal Bookworm caches the book contents in ~/.config/bookworm/books if caching is enabled for faster opens. 
Otherwise (if cache is not enabled) only the location of the book is stored and it extracted every time it is opened for reading and the extracted contents are kept in /tmp/bookworm which is removed on restart of the machine.

Hence in either case, the ebook file is not duplicated by bookworm on import. The cached contents are closest to an "import" in my opinion as it removes the necessity of the ebook file to be available for reading.

**Comment by babluboy** [comment]
Pushed the code for the preference item to add multiple folders to watch for books and add them into bookworm automatically if the book format is supported...
![screenshot from 2017-06-12 22 49 36](https://user-images.githubusercontent.com/14061478/27056838-9aa0f638-4fc1-11e7-9152-f33eb8dbae1c.png)
