### ISSUE TITLE
Two page view

### ISSUE THREAD

**Issue by lecroix74** [babluboy/bookworm#79]
i don't seem to be able to find it...can we have two-page view (side by side)?

**Comment by babluboy** [comment]
@lecroix74 Two page view is not built yet. Will add this to the To-Do list and will use this issue to track the same...

**Comment by babluboy** [comment]
Pushed a update to add a preference item to enable two-page-view...The implementation divides the content on the page into two pages rather than show two chapters side by side...this makes more sense IMHO for bookworm which shows the whole chapter in a vertically scrollable page...

still needs a bit more work to render pages where there is not enough text to divide the page content into two sections and also comics need work to ensure pictures are places in two columns rather than a single column in 50% width...

![two page view 1](https://user-images.githubusercontent.com/14061478/29001557-843e79bc-7a85-11e7-984d-11df104f0136.png)

**Comment by babluboy** [comment]
Fixed the issue of not going into the two page view (even though it is enabled in the preference settings) if the number of characters to display is less then a minimum value
The two page view is now at a working level for an initial release with other stuff.
