### ISSUE TITLE
Too much white space

### ISSUE THREAD

**Issue by nloomans** [babluboy/bookworm#92]
First of, thanks for making bookworm! It's a great book reader.

However, I have noticed that some books have a lot of extra white space on sort of random spaces. Here are some screenshots:
![Screenshot showing how the extra white space](https://user-images.githubusercontent.com/7829481/27768238-97bf193e-5f0e-11e7-92dd-604ca63fd40b.png)
![Second screenshot showing more](https://user-images.githubusercontent.com/7829481/27768240-a050081a-5f0e-11e7-8c45-0950650e6127.png)

I unfortunately can't share the document thru GitHub because of copyright, so I've send you an email.

**Comment by babluboy** [comment]
@nloomans Thanks for raising this - I can see the issue on some of my books as well as well as on the book you sent. I'm suspecting that the formatting I've set on the last v0.8 release is clashing with the format in the book ...will look into this as part of the next release and keep you posted...
N.B: Thanks for supporting Bookworm :-)

**Comment by babluboy** [comment]
That wasn't so hard to fix - the "margin-right" and "margin-left" controls imposed by the code were clashing with the same in the book's css. Instead of using margin-left/right I have used "max-width" to control the line width - this seems to be working with a few books that I have tested including the one you sent.

Pushed the code changes to master now and this should be out on AppCenter as part of the next update (v0.9)...If you are ok to build from source then you can use the instructions [here](https://github.com/babluboy/bookworm#how-to-build-bookworm) to get the fix. 
![screenshot from 2017-07-02 13 19 14](https://user-images.githubusercontent.com/14061478/27769849-18397656-5f2b-11e7-83f7-3bca193e4028.png)

**Comment by nloomans** [comment]
Thanks a lot!
