### ISSUE TITLE
Allow to sort books by progress in the list view

### ISSUE THREAD

**Issue by Anne017** [babluboy/bookworm#96]
I wish I could sort books by progress in the list view.
I often start to read a couple of books in parallel, this way I could identify very quickly the one I finished from the others.
Nice work on this app by the way!

**Comment by babluboy** [comment]
@Anne017 Good thought, I can add a progress column on the List View. However, you can sort the books by Last Read and that should bring the books you opened recently to the top..

In fact, since anyone would hardly read more than five books in parallel, does it makes much sense to keep a column for progress? Other than the first five, everything would be either 100% or 0% - sorting by last read time would pretty much give the same results....let me know your thoughts

**Comment by Anne017** [comment]
Touché! It makes sense.
For the shake of the "Keep It Simple, Stupid" concept of Elementary OS, we should probably close this issue.

**Comment by babluboy** [comment]
Thanks :-)
